services:
  - type: web
    name: rischis-kiosk
    env: node
    plan: free
    rootDir: kiosk-backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    region: frankfurt

  - type: web
    name: rischis-kiosk-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
    region: frankfurt
